services:
  postgres:
    image: postgres:15
    container_name: postgres_tech_trend_dev
    environment:
      POSTGRES_DB: techtrend-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: